name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${{ GITHUB_REF:10 }})

      - name: Build the tagged Docker image
        run: docker build --build-arg VERSION=${{ steps.vars.outputs.tag }} -t ${{ secrets.DOCKER_USERNAME }}/openapi-generator-cli-custom:${{ steps.vars.outputs.tag }} -f Dockerfile .
            
      - name: Push the tagged Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/openapi-generator-cli-custom:${{ steps.vars.outputs.tag }}
